---
title: "GenerateSamples"
author: "Sam Su"
date: "2/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(370)
library(tidyverse)
```

Generate 100 samples, of 80%-20% SAS vs neutral split
```{r}
samples <- 100
# shuffle the sample ids
shuffled_indices <- sample(seq(1, samples), size = samples)
# 80-20 split
SAS <- round(0.2 * samples)
SAS_indices <- shuffled_indices[1:SAS]
No_indices <- shuffled_indices[SAS+1:samples] %>% na.omit()
```

```{r}
for (i in seq(1, samples)) {
  filename <- paste0("./input/input", i)
  sink(filename)
  cat(paste0(i, "\n"))        # first number is just n, the number used by the ABC package
  cat(paste0(100, "\n"))      # recombination rate, holding it constant at 100 at the moment
  if (i %in% SAS_indices) {
    # the frequency of the SA allele on the 14 X chromosomes (rand from 0.1 to 0.2)
    cat(paste0(runif(1, 0.1, 0.2), "\n"))
    # the frequency of the SA allele on the 14 Y chromosomes (rand from 0.8 to 0.9)
    cat(paste0(runif(1, 0.8, 0.9), "\n"))
  }
  else {
    # neutral simulation
    cat(paste0(0, "\n"))
    cat(paste0(0, "\n"))
  }
  # SAS location (in rho) from the SDR (in real world unknown, rand from 75 to 200)
  cat(paste0(sample(75:200, 1), "\n"))      
  sink()
}

label_df <- data.frame(
  indices = shuffled_indices,
  SAS = c(rep("Yes", SAS), rep("No", samples - SAS))
)
write.csv(label_df, file = "./output/label.csv", row.names = F)
```

